---
title: "Webbutveckling 2"
date: "2019-12-02"
---

Den här kursen går ut på att förfina och utveckla dina kunskaper och förmågor att skapa webbsidor och webbapplikationer.

I kursen kommer du lära dig:

- [Responsiv design](https://sv.wikipedia.org/wiki/Responsiv_webbdesign)
- Utvecklingsmetodik för webbapplikationer
- Hur man utvecklar grundläggande webbapplikationer
- Avancerade metoder i HTML och CSS
- Använda JavaScript för att skapa interaktivitet
- Skapa webbanimeringar och användandet av [SVG](https://sv.wikipedia.org/wiki/Scalable_Vector_Graphics)
- Hur man testar sin hemsida, automatiskt och manuellt
- Grundläggande automatisering av minifiering och konkatinering (och vad det innebär)
- Bildoptimering och spriting

# Översikt för kursupplägget

- Genomgångar och laborationer
- Många småprojekt
- Större projekt

# Centralt innehåll:

- Webben som plattform för applikationer av olika slag.

- Utvecklingsprocessen för ett webbtekniskt projekt med målsättningar, planering, specifikation av struktur och design, kodning, optimering, testning, dokumentation och uppföljning.

- Fördjupning i märkspråk där det huvudsakliga innehållet är standarderna för HTML och CSS med särskilt fokus på responsiv design.

- Språk med stöd för variabler för att förenkla CSS-generering.

- Ramverk eller klassbibliotek inom design eller skriptspråk.

- Skriptspråk för webbutveckling på klientsidan och dokumentobjektsmodell.

- Bilder, ljud, video och två- eller tredimensionell interaktiv grafik för webbapplikationer.

- Riktlinjer för god praxis inom webbutveckling.

- Uppnående av interoperabilitet genom att följa standarder och testa på olika plattformar.

- Applikationer som fungerar oberoende av vald plattform och hur tillgänglighet uppnås även för användare med funktionsnedsättning.

- Kvalitetssäkring av applikationens funktion och validering av kodens kvalitet.

- Lagar och andra bestämmelser som styr digital information, till exempel personuppgiftslagen och lagen om elektronisk kommunikation.

- Säkerhet och sätt att identifiera hot och sårbarheter samt hur attacker kan motverkas genom effektiva åtgärder.

- Terminologi inom området webbutveckling.

# Kunskapskrav

| E                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | C                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | A                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Eleven beskriver **översiktligt** webben som plattform samt gör en **enkel** jämförelse med **något** annat alternativ.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | Eleven beskriver **utförligt** webben som plattform samt gör en **välgrundad** jämförelse med **några** andra alternativ.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | Eleven beskriver **utförligt** och **nyanserat** webben som plattform samt gör en **välgrundad** och **nyanserad** jämförelse med flera andra alternativ.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| Eleven gör en **enkel** projektplan för en tänkt produkt. Utifrån projektplanen utvecklar eleven i **samråd** med handledare produkten där logiker som styr innehåll, design och beteende i **begränsad utsträckning** är åtskilda. I arbetet utvecklar eleven kod som med **tillfredsställande** resultat följer standarder och som omfattar **någon** teknik för märkspråk och stilmallar där eleven i **begränsad utsträckning** använder tekniker för att generera stilmallskod. I arbetet bearbetar eleven med **tillfredsställande** resultattext, bild och eventuell annan media så att de blir anpassade för att fungera i produkten. Eleven utvecklar med **tillfredsställande** funktionalitet inom något eller några av områdena domskript, interaktiv 2D-grafik, 3D-grafik eller animationer. I sitt arbete inkluderar eleven någon **enkel funktion** från ett klassbibliotek eller ramverk inom områdena design eller skript. | Eleven gör en **genomarbetad** projektplan för en tänkt produkt. Utifrån projektplanen utvecklar eleven **efter samråd** med handledare produkten där logiker som styr innehåll, design och beteende är åtskilda. I arbetet utvecklar eleven kod som med **tillfredsställande** resultat följer standarder och som omfattar **några** tekniker för märkspråk och stilmallar där eleven använder tekniker för att generera stilmallskod. I arbetet bearbetar eleven med **tillfredsställande** resultat och **via flera moment** text, bild och eventuell annan media så att de blir anpassade för att fungera i produkten. Eleven utvecklar med **tillfredsställande** resultat funktionalitet inom något eller några av områdena domskript, interaktiv 2D-grafik, 3D-grafik eller animationer. I sitt arbete inkluderar eleven **några** funktioner från ett klassbibliotek eller ramverk inom områdena design eller skript. | Eleven gör en **genomarbetad** projektplan för en tänkt produkt, **vid behov reviderar eleven planen**. Utifrån projektplanen utvecklar eleven **efter samråd** med handledare produkten där logiker som styr innehåll, design och beteende i **omfattande utsträckning** är åtskilda. I arbetet utvecklar eleven kod som med **gott** resultat följer standarder och som omfattar **flera** tekniker för märkspråk och stilmallar där eleven i **omfattande utsträckning** använder tekniker för att generera stilmallskod. I arbetet bearbetar eleven med **gott** resultat och **via flera moment** text, bild och eventuell annan media så att de blir anpassade för att fungera i produkten. Eleven utvecklar med **gott** resultat funktionalitet inom något eller några av områdena domskript, interaktiv 2D-grafik, 3D-grafik eller animationer. I sitt arbete inkluderar eleven **flera** funktioner av **komplex natur** från ett klassbibliotek eller ramverk inom områdena design eller skript. |
| Produkten är av **tillfredsställande** kvalitet när det gäller funktion vilket eleven kontrollerar med hjälp av **någon** test. Dessutom kontrollerar eleven **med viss säkerhet** produktens tillgänglighet med automatiserade tester. Eleven vidtar **någon** åtgärd för att åstadkomma snabb överföring av bilder och andra mediafiler.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Produkten är av **tillfredsställande** kvalitet när det gäller funktion vilket eleven kontrollerar med hjälp av **några** tester. Dessutom kontrollerar eleven med **viss säkerhet** produktens tillgänglighet med automatiserade tester och **begränsad manuell testning**. Eleven vidtar **några** åtgärder för att åstadkomma snabb överföring av bilder och andra mediafiler.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | Produkten är av **god** kvalitet när det gäller funktion vilket eleven kontrollerar med hjälp av **flera** tester, **även manuella**. Dessutom kontrollerar eleven **med säkerhet** produktens tillgänglighet med automatiserade tester **och simuleringar samt manuella tester**. Eleven vidtar **optimeringar av** bilder och andra mediafiler för att åstadkomma snabb överföring av dessa och **vidtar åtgärder för att reducera antalet överföringar per sida**.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| När arbetet är utfört gör eleven en **enkel** dokumentation av de moment som har utförts samt utvärderar med **enkla** omdömen sitt arbete och resultat. Eleven redogör **översiktligt** för innehållet i lagar och andra bestämmelser som rör publicering på webben samt följer dem i sitt arbete. Dessutom för eleven **enkla** resonemang kring webbrelaterade frågor om etik och integritet. Eleven tar hänsyn till säkerhetsaspekter i sitt arbete och i fråga om produkten samt kontrollerar produktens säkerhet med någon test. Eleven använder med **viss säkerhet** terminologi inom området.                                                                                                                                                                                                                                                                                                                                      | När arbetet är utfört gör eleven en **noggrann** dokumentation av de moment som har utförts samt utvärderar med **nyanserade** omdömen sitt arbete och resultat. I utvärderingen resonerar eleven kring eventuella avvikelser samt motiverar översiktligt de val som har gjorts. Eleven redogör utförligt för innehållet i lagar och andra bestämmelser som rör publicering på webben samt följer dem i sitt arbete. Dessutom för eleven välgrundade resonemang kring webbrelaterade frågor om etik och integritet. Eleven tar hänsyn till säkerhetsaspekter i sitt arbete och i fråga om produkten samt kontrollerar produktens säkerhet med några tester. Eleven använder med **viss säkerhet** terminologi inom området.                                                                                                                                                                                                   | När arbetet är utfört gör eleven en **noggrann och utförlig** dokumentation av de moment som har utförts **med koppling till generella principer och testresultat** samt utvärderar med **utförliga och nyanserade** omdömen sitt arbete och resultat **samt ger förslag på hur arbetet kan förbättras**. **I utvärderingen resonerar eleven kring eventuella avvikelser samt motiverar utförligt de val som har gjorts.** Eleven redogör **utförligt och nyanserat** för innehållet i lagar och andra bestämmelser som rör publicering på webben samt följer dem i sitt arbete. Dessutom för eleven **välgrundade och nyanserade** resonemang kring webbrelaterade frågor om etik och integritet. Eleven tar hänsyn till säkerhetsaspekter i sitt arbete och i fråga om produkten samt kontrollerar produktens säkerhet med flera tester. Eleven använder **med säkerhet terminologi** inom området.                                                                                                       |

Källa: [Skolverkets hemsida](https://www.skolverket.se/undervisning/gymnasieskolan/laroplan-program-och-amnen-i-gymnasieskolan/gymnasieprogrammen/amne?url=1530314731%2Fsyllabuscw%2Fjsp%2Fsubject.htm%3FsubjectCode%3DWEU%26courseCode%3DWEUWEB01%26tos%3Dgy&sv.url=12.5dfee44715d35a5cdfa92a3#anchor_WEUWEB01)

##Program och verktyg

- **[Visual Studio Code](https://code.visualstudio.com/)**: Man kan tekniskt sett skriva HTML, CSS, och JavaScript i vilket anteckningsprogram som helst, så länge den bara sparar filen i ren text. Men VSC kommer med en mängd funktioner som gör utvecklingsprocessen mycket enklare.
- **[Figma](https://www.figma.com)**: Figma är ett UI-design program som gör att vi snabbt kan skapa en design för en hemsida.
- **[Chrome](https://www.google.com/intl/sv/chrome/) eller [Firefox](https://www.mozilla.org/sv-SE/firefox/new/) web developer tools**: Både Chrome och Firefox har webbutvecklarverktyg som vi kommer använda för att inspektera hemsidors kod, och hitta och lösa problem. Dessa kommer du via respektive webbläsare.

#Resurser

- **[MDN Web Docs](https://developer.mozilla.org/sv-SE/)** MDN Web Docs är en platform som innehåller en gigantisk mängd information om HTML, CSS, och JavaScript, inklusive guider, referensmaterial och information om hur teknikerna fungerar.
- **[W3C Validator](https://validator.w3.org/)** Vi kommer använda detta verktyg för att validera vår HTML.
- **[CSS Validator](https://jigsaw.w3.org/css-validator/)** Vi kommer använda detta verktyg för att validera vår CSS.
- **[ColorDesigner.io](https://colordesigner.io/)**: Används för att hämta färger.
- **[Dribbble](https://dribbble.com/)**: Designinspiration.
- **[Land-book](https://land-book.com/)**: Designinspiration.
